import { Fragment } from "react";
import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
import HeroBadge from "@/components/HeroBadge";
import YoutubeLite from "@/components/YoutubeLite";
import VisibilityChart from "@/components/VisibilityChart";
import SectionHeading from "@/components/SectionHeading";
import GoogleColors from "@/components/GoogleColors";
import ClientResultsWidget from "@/components/ClientResultsWidget";
import { REVIEWS } from "@/data/reviews";
import ReviewCard from "@/components/ReviewCard";
import GuaranteesCards from "@/components/GuaranteesCards";
import EscalierReveal from "@/components/EscalierReveal";
import FadeUp from "@/components/FadeUp";
import TypewriterText from "@/components/TypewriterText";
import TrustedPartners from "@/components/TrustedPartners";
import AccompagnementsTeaser from "@/components/AccompagnementsTeaser";
import SiteHeader from "@/components/SiteHeader";

export const metadata: Metadata = {
  title: "JWL Marketing | Digital Marketing in Aix-en-Provence",
  description:
    "Tired of an invisible website? Discover my world built around client acquisition, SEO and AI. Based in Aix-en-Provence, working across France.",
};

const METHODE_STEPS = [
  {
    image: "/images/accompagnement-digital.png",
    title: "I find out",
    lead: "I identify why Google isn't bringing you enough clients.",
    items: [
      "SEO audit",
      "Sales audit",
      "Competitor analysis",
      "Google Business Profile analysis",
    ],
    cta: "Book a call",
    href: "/en/contact-jwl-marketing-aix-en-provence",
  },
  {
    image: "/images/strategie-marketing.png",
    title: "I take action",
    lead: "I build an ecosystem that works for your business.",
    items: [
      "Google Business Profile",
      "Website",
      "SEO pages",
      "Blog articles",
      "AI and GEO optimisation",
    ],
    cta: "Learn more",
    href: "/en/site-internet-aix-en-provence",
  },
  {
    image: "/images/developpement-digital.png",
    title: "Google finds you",
    lead: "I measure, adjust and grow your visibility.",
    items: [
      "Ranking tracking",
      "Performance analysis",
      "New SEO opportunities",
      "Monthly support",
    ],
    cta: "Learn more",
    href: "/en/audit-seo-aix-en-provence",
  },
];

export default function Home() {
  return (
    <div>
      <SiteHeader locale="en" href="/" />

      {/* Hero */}
      <div className="flex w-full flex-col items-start justify-between gap-10 bg-white px-[6%] pb-[60px] pt-[90px] lg:flex-row lg:gap-24 lg:px-[9%]">
        <div className="max-w-[720px] flex-1">
          <h1 className="m-0 mb-1 font-heading text-5xl font-extrabold leading-[1.02] text-black lg:text-[76px] lg:leading-[1.02]">
            <span className="font-heading italic text-[#c9846f]">
              Be visible
            </span>
            <span> where your future clients are looking for you. </span>
          </h1>

          <p className="mt-2.5 text-2xl leading-[1.5] text-[#333]">
            Measure the number of clicks, quote request calls or contacts,
            and the traffic generated by your online presence
          </p>

          <div className="mt-6 flex flex-wrap gap-[15px]">
            <a
              href="tel:0783792814"
              className="inline-block rounded-full bg-[#c9846f] px-9 py-[18px] text-lg font-medium text-white transition-colors hover:bg-[#b8735f]"
            >
              07 83 79 28 14
            </a>
            <Link
              href="/en/contact-jwl-marketing-aix-en-provence"
              className="inline-block rounded-full bg-[#faf3ea] px-9 py-[18px] text-lg font-medium text-[#c9846f] transition-colors hover:bg-[#f2e6d4]"
            >
              FREE Marketing Audit
            </Link>
          </div>

          <div className="mt-6 flex flex-wrap items-center gap-2 text-base">
            <span className="text-lg font-normal text-[#1a2b6b]">5/5</span>
            <span className="text-gold">★★★★★</span>
            <span className="text-[#555]">16 Google reviews</span>
            <span className="text-[#999]">·</span>
            <a
              href="http://api.jwl-marketing.fr/redirects/gmb/jwl.html"
              target="_blank"
              rel="noopener"
              className="font-normal text-[#1a2b6b] underline"
            >
              Add a review
            </a>
          </div>
        </div>

        <div className="hidden w-full flex-1 items-start justify-center sm:flex sm:h-[380px] lg:h-[460px] lg:justify-end">
          <div className="relative h-full w-auto">
            <video
              src="/videos/hero-jodie-etoile.mp4"
              autoPlay
              loop
              muted
              playsInline
              aria-label="Jodie Lapaillerie - JWL Marketing"
              className="relative z-10 h-full w-auto max-w-none object-contain"
            />
            <HeroBadge />
          </div>
        </div>
      </div>

      <TrustedPartners />

      {/* What if your next client... */}
      <section className="flex flex-col items-center justify-between gap-10 px-[5%] py-20 md:flex-row">
        <FadeUp className="flex-[1.4_1_0%] overflow-hidden rounded-[40px] bg-black p-10">
          <div className="mx-auto aspect-video w-full max-w-[650px] overflow-hidden rounded-xl">
            <YoutubeLite videoId="-btM09DQ4zg" title="JWL Marketing" />
          </div>
        </FadeUp>
        <FadeUp delay={0.15} className="flex flex-1 flex-col items-center justify-center text-center">
          <h2 className="mx-auto max-w-[560px] font-heading text-3xl font-normal leading-[1.2] text-black md:text-[54px] md:leading-[1.1]">
            What if <span className="italic text-[#c9846f]">your next</span>
            <br />
            <span className="italic text-[#c9846f]">client</span> found you
            <br />
            thanks to <GoogleColors />
            <span className="text-black">?</span>
          </h2>
          <p className="mx-auto mt-6 max-w-[480px] text-justify text-lg leading-relaxed text-black/85">
            Former sales rep at the IAC group (Meetic, TripAdvisor,
            Travaux.com), I apply the same principles that drive sales on the
            ground to digital: understand your market, stand out and
            convert.
          </p>
        </FadeUp>
      </section>

      {/* Client case */}
      <section className="px-[5%] py-16 text-center">
        <FadeUp>
          <SectionHeading title="What JWL MARKETING put in place">
            <br />
            for one of{" "}
            <span className="italic text-[#c9846f]">these clients</span>
          </SectionHeading>
          <ClientResultsWidget />
        </FadeUp>
      </section>

      {/* Choose the support adapted to your project */}
      <section className="px-[5%] py-16 text-center">
        <FadeUp>
          <SectionHeading
            kicker="Choose the support"
            title="that fits your project"
            subtext={
              <span className="block text-justify text-lg text-black/85">
                Your business evolves, and so do your needs. Start with a
                professional website, grow your visibility on Google, attract
                more prospects, or strengthen your sales development with
                support tailored to every stage of your growth.
              </span>
            }
          />
        </FadeUp>
        <AccompagnementsTeaser pair="primary" locale="en" />
        <div className="mt-8 text-center">
          <Link
            href="/en/site-internet-aix-en-provence"
            className="inline-block rounded-full bg-[#c9846f] px-8 py-[15px] font-medium text-white transition-colors hover:bg-[#b8735f]"
          >
            Create my website
          </Link>
        </div>
      </section>

      {/* The method */}
      <section className="px-[5%] py-16 text-center">
        <SectionHeading kicker="The method" title="JWL MARKETING" />
        <EscalierReveal
          className="mx-auto grid max-w-[1200px] gap-6 md:grid-cols-3"
          itemClassName="flex flex-col overflow-hidden rounded-2xl bg-black text-white transition-all duration-300 hover:-translate-y-8 hover:shadow-2xl"
        >
          {METHODE_STEPS.map((step, i) => (
            <Fragment key={step.title}>
              <Image
                src={step.image}
                alt={step.title}
                width={455}
                height={340}
                className="h-[220px] w-full object-cover"
              />
              <div className="border-b border-white/15 px-6 py-6">
                <h3 className="min-h-[1.6em] font-heading text-xl">
                  <TypewriterText text={step.title} speed={35} startDelay={i * 100 + 350} />
                </h3>
                <p className="mt-3 text-justify text-lg text-white/85">{step.lead}</p>
              </div>
              <ul className="flex-1 space-y-2 px-6 py-6 text-sm text-white/85">
                {step.items.map((item) => (
                  <li key={item}>{item}</li>
                ))}
              </ul>
              <div className="px-6 pb-8 text-center">
                <Link
                  href={step.href}
                  className="inline-block rounded-full bg-[#c9846f] px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-[#b8735f]"
                >
                  {step.cta}
                </Link>
              </div>
            </Fragment>
          ))}
        </EscalierReveal>
      </section>

      {/* Why businesses choose JWL Marketing */}
      <section className="px-[5%] py-16 text-center">
        <FadeUp>
          <SectionHeading kicker="Why businesses choose" title="JWL MARKETING ?" />
        </FadeUp>
        <GuaranteesCards />
      </section>

      {/* Your visibility isn't a matter of luck */}
      <section className="px-[5%] py-16 text-center">
        <SectionHeading
          kicker="Your visibility"
          title="grows thanks to the clients your website generates."
        />

        <FadeUp className="mx-auto flex max-w-[1200px] flex-col items-center gap-10 md:flex-row md:items-stretch">
          <div className="flex w-full shrink-0 items-center justify-center md:w-auto">
            <VisibilityChart />
          </div>
          <div className="w-full rounded-2xl p-8 text-left text-black md:p-10">
            <p className="text-justify text-lg leading-relaxed text-black/85">
              My job isn&apos;t limited to building websites. It&apos;s about
              helping you build a genuine digital ecosystem to grow your
              business and attract new clients.
            </p>
            <p className="mt-4 text-justify text-lg leading-relaxed text-black/85">
              My role is to create a link between your everyday life as an
              entrepreneur and digital tools. Whether you&apos;re
              prospecting, attending trade shows, or out in the field, the
              goal is to keep your business visible and generating
              opportunities, even when you&apos;re not behind a screen.
            </p>
            <p className="mt-4 text-justify text-lg leading-relaxed text-black/85">
              To do this I use the digital tools best suited to your
              business: optimised website, search engine optimisation (SEO),
              Google Business Profile, content, articles, blog, AI, and other
              visibility levers. Every action is designed to strengthen your
              online presence, build your credibility and help you win new
              clients.
            </p>
          </div>
        </FadeUp>

        {/* Want to go further? */}
        <FadeUp>
          <SectionHeading title="Want to go further?" />
          <p className="mx-auto max-w-[720px] text-justify text-lg leading-relaxed text-black/85">
            <strong className="text-black">JWL Connect</strong>: For
            businesses that want to publish SEO-optimised content regularly
            and strengthen their visibility.
            <br />
            <strong className="text-black">JWL Prospecte</strong>: For
            businesses that want to grow their sales acquisition and B2B
            prospecting.
          </p>
        </FadeUp>
        <div className="mt-10">
          <AccompagnementsTeaser pair="secondary" locale="en" />
        </div>
        <div className="mt-8 text-center">
          <Link
            href="/en/contact-jwl-marketing-aix-en-provence"
            className="inline-block rounded-full bg-[#c9846f] px-8 py-[15px] font-medium text-white transition-colors hover:bg-[#b8735f]"
          >
            Start my project
          </Link>
        </div>

        <SectionHeading
          kicker="What's next?"
          title="we keep going together, or on your own"
        />
        <FadeUp>
          <div className="mx-auto max-w-[900px] rounded-2xl p-8 text-left text-black md:p-10">
            <p className="text-justify text-lg leading-relaxed text-black/85">
              You&apos;re free to keep working with JWL Marketing, manage
              your communication on your own, or work with another provider.
              The tools, the data and the work delivered remain yours. At JWL
              Marketing, you keep all your accesses and tools.
            </p>
          </div>
          <Image
            src="/images/jwl-et-apres-jwl-marketing.png"
            alt="JWL Marketing - we keep going together"
            width={900}
            height={450}
            className="mx-auto mt-8 h-auto w-full max-w-[500px] object-contain"
          />
        </FadeUp>
      </section>

      {/* Testimonials */}
      <section className="bg-neutral-50 px-6 py-16">
        <div className="mx-auto my-10 max-w-[700px] px-5 text-center md:my-[60px]">
          <h2 className="font-heading text-3xl leading-[1.2] md:text-[54px] md:leading-[1.35]">
            <span className="italic text-[#c9846f]">They&apos;re cashing in,</span>{" "}
            <span className="text-black">with JWL MARKETING</span>
          </h2>
        </div>
        <EscalierReveal
          className="mx-auto flex max-w-[1200px] gap-6 overflow-x-auto px-2 pb-4"
          itemClassName="shrink-0"
        >
          {REVIEWS.map((r) => (
            <ReviewCard key={r.name} {...r} />
          ))}
        </EscalierReveal>
      </section>
    </div>
  );
}
